### ISSUE TITLE
Document: How to update template repo

### ISSUE THREAD

**Issue by hashrock** [denoland/remix_template#1]
Pointing to this repository from Deno deploy's `Start with a template` will carry over the commits.
So we want this repository to always have only one initial commit. It should be under denobot name.

Also, please describe how you generated the repository and the commands you used in the README or issue.

# Examples

## Renew assets

```sh
TMP_DIR=$(mktemp -d)
npx create-remix@latest --template deno $TMP_DIR
rsync -av --progress $TMP_DIR/ ./ --exclude node_modules
rm -rf $TMP_DIR
git status
```

**Comment by kt3k** [comment]
Let's close this one as we decided to do this in a different repo
